"""Summarise results/<device>-run-NNN.json into results/summary.json and results/SUMMARY.md.

    uv run python summarize.py

Every run is included; nothing is dropped as an outlier. Latency percentiles are computed over
every decision of every run of a device (linear interpolation, numpy's default), and each run's
own P50/P95 is listed so the spread between runs stays visible. Latency is laya-apple's
RuntimeInfo.latency_ms: from the predict() call to the result, on the device that ran it.
"""

import argparse
import glob
import json
import os

import numpy as np

ROOT = os.path.dirname(os.path.abspath(__file__))
RES = os.path.join(ROOT, "results")
NAMES = {"gpu": "MLX GPU", "ane": "Apple Neural Engine"}


def pct(xs, p):
    return round(float(np.percentile(xs, p)), 3)


def load(res, device):
    runs = []
    for path in sorted(glob.glob(os.path.join(res, "%s-run-*.json" % device))):
        with open(path) as f:
            runs.append(json.load(f))
    return runs


def device_summary(runs):
    lat = np.array([d[3] for r in runs for d in r["decisions"]])
    s = [r["summary"] for r in runs]

    def col(k):
        return [x[k] for x in s]

    first_crash = [x["speed_at_first_crash"] for x in s if x["speed_at_first_crash"] is not None]
    actions = {k: sum(x["action_counts"][k] for x in s) for k in ("STAY", "LEFT", "RIGHT")}
    return {
        "runs": len(runs),
        "seeds": [r["seed"] for r in runs],
        "decisions": int(lat.size),
        "latency_ms": {"mean": round(float(lat.mean()), 3), "p50": pct(lat, 50), "p95": pct(lat, 95), "p99": pct(lat, 99),
                       "min": round(float(lat.min()), 3), "max": round(float(lat.max()), 3)},
        "per_run_latency_ms": [{"seed": r["seed"], "p50": pct([d[3] for d in r["decisions"]], 50),
                                "p95": pct([d[3] for d in r["decisions"]], 95), "p99": pct([d[3] for d in r["decisions"]], 99)} for r in runs],
        "score_final": col("score"), "best_score": col("best"), "rows_cleared": col("rows_cleared"), "crashes": col("crashes"),
        "survival_seconds": col("survival_seconds"), "distance": col("distance"),
        "decisions_per_run": col("decisions"), "decisions_per_game_second": col("decisions_per_game_second"),
        "decisions_per_wall_second": col("decisions_per_wall_second"),
        "max_speed": col("max_speed"), "speed_at_first_crash": col("speed_at_first_crash"),
        "runs_with_a_crash": len(first_crash), "total_crashes": int(sum(col("crashes"))),
        "action_counts": actions, "choice_argmax_disagreements": int(sum(col("choice_argmax_disagreements"))),
        "sequence_lengths": sorted({n for x in s for n in x["sequence_lengths"]}),
        "routing_reasons": sorted({n for x in s for n in x["routing_reasons"]}),
    }


def outcome_diff(gpu, ane):
    """Per seed: did the two devices produce the same game?"""
    by = {r["seed"]: r for r in ane}
    rows = []
    for g in gpu:
        a = by.get(g["seed"])
        if a is None:
            continue
        # a decision is (step observed, step applied, action); probabilities differ in the last FP16 bits by design
        stream = lambda r: [(d[0], d[1], act) for d, act in zip(r["decisions"], r["actions"])]  # noqa: E731
        rows.append({"seed": g["seed"],
                     "gpu": {k: g["summary"][k] for k in ("rows_cleared", "crashes", "decisions", "max_speed")},
                     "ane": {k: a["summary"][k] for k in ("rows_cleared", "crashes", "decisions", "max_speed")},
                     "same_decision_steps": [d[:2] for d in g["decisions"]] == [d[:2] for d in a["decisions"]],
                     "identical_decision_stream": stream(g) == stream(a)})
    return rows


def md(summary):
    g, a = summary["devices"].get("gpu"), summary["devices"].get("ane")
    L = ["# Lane Runner on laya-apple: MLX GPU vs Apple Neural Engine", "",
         "Generated by `summarize.py` from `results/*-run-*.json`. Do not edit by hand.", "",
         "Model `%s`, %d runs per device, %d game seconds each, seeds %s. Every run is included." % (
             summary["model"], summary["runs_per_device"], summary["seconds"], summary["seeds"]), ""]
    L += ["## Latency (laya-apple `RuntimeInfo.latency_ms`, all decisions of all runs)", "",
          "| Device | Decisions | Mean | P50 | P95 | P99 | Max |", "|---|---:|---:|---:|---:|---:|---:|"]
    for dev, s in (("gpu", g), ("ane", a)):
        if s:
            x = s["latency_ms"]
            L.append("| %s | %d | %.2f ms | %.2f ms | %.2f ms | %.2f ms | %.2f ms |" % (NAMES[dev], s["decisions"], x["mean"], x["p50"], x["p95"], x["p99"], x["max"]))
    L += ["", "## Game", "", "| Device | Rows cleared (median, min–max) | Crashes (total) | Runs with a crash | Max speed | Decisions / game s | Decisions / wall s (median) |",
          "|---|---|---:|---:|---:|---:|---:|"]
    for dev, s in (("gpu", g), ("ane", a)):
        if s:
            rc = s["rows_cleared"]
            L.append("| %s | %g (%g–%g) | %d | %d / %d | %.2f | %.2f | %.1f |" % (
                NAMES[dev], np.median(rc), min(rc), max(rc), s["total_crashes"], s["runs_with_a_crash"], s["runs"],
                max(s["max_speed"]), np.median(s["decisions_per_game_second"]), np.median(s["decisions_per_wall_second"])))
    L += ["", "Actions: " + "; ".join("%s %s" % (NAMES[d], json.dumps(s["action_counts"])) for d, s in (("gpu", g), ("ane", a)) if s), ""]
    if summary.get("per_seed"):
        same = sum(r["identical_decision_stream"] for r in summary["per_seed"])
        L += ["## Same seed, same game?", "",
              "%d of %d seeds produced an identical stream of decisions on both devices: the same action at the same game step, every time." % (same, len(summary["per_seed"])), "",
              "| Seed | GPU rows / crashes | ANE rows / crashes | Same decision steps | Same actions |", "|---|---|---|---|---|"]
        for r in summary["per_seed"]:
            L.append("| %d | %d / %d | %d / %d | %s | %s |" % (r["seed"], r["gpu"]["rows_cleared"], r["gpu"]["crashes"], r["ane"]["rows_cleared"],
                                                            r["ane"]["crashes"], "yes" if r["same_decision_steps"] else "no", "yes" if r["identical_decision_stream"] else "no"))
    L += ["", "## Method", "", summary["method"], ""]
    return "\n".join(L)


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--results", default=RES)
    res = ap.parse_args().results
    runs = {d: load(res, d) for d in ("gpu", "ane")}
    ref = next(r for rs in runs.values() for r in rs)
    summary = {
        "model": ref["model"], "seconds": ref["seconds"], "runs_per_device": max(len(r) for r in runs.values()),
        "seeds": sorted({r["seed"] for rs in runs.values() for r in rs}),
        "params": ref["params"], "step_s": ref["step_s"], "max_rate": ref["max_rate"],
        "environment": {d: {k: rs[0]["server"].get(k) for k in ("soc", "laya_apple", "mlx", "coremltools", "python", "macos")} for d, rs in runs.items() if rs},
        "devices": {d: device_summary(rs) for d, rs in runs.items() if rs},
        "per_seed": outcome_diff(runs["gpu"], runs["ane"]) if runs["gpu"] and runs["ane"] else [],
        "method": ("The upstream Lane Runner (static/demos/runner.js, unchanged) is stepped headlessly at 1/120 s. "
                   "One request is in flight at a time; while it is, the game advances by the measured HTTP round trip "
                   "rounded up to whole steps, then the action is applied (upstream tools/record_run.mjs). Decisions are "
                   "capped at 40 per game second, as in the browser. Each device is measured in its own server process "
                   "with only that device loaded, one after the other, never concurrently."),
    }
    with open(os.path.join(res, "summary.json"), "w") as f:
        json.dump(summary, f, indent=1)
    with open(os.path.join(res, "SUMMARY.md"), "w") as f:
        f.write(md(summary))
    print(md(summary))


if __name__ == "__main__":
    main()
